[tool.poetry]
name = "terraframe"
version = "0.0.1"
description = "A tiny, highly opinionated Terraform framework"
authors = ["André Lima"]
license = "Apache 2.0"
readme = "README.md"
packages = [{include = "terraframe"}]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^2.4.2"
pyyaml = "^6.0.1"
jinja2 = "^3.1.2"
sortedcontainers = "^2.4.0"


[tool.poetry.group.dev.dependencies]
black = "^23.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
